trigger: none

resources:
  pipelines:
    - pipeline: ainewsfeather-create-artifacts-pip # Name of the pipeline resource
      source: 02-AiNewsFetcher-Create-Artifacts # Name of the pipeline referenced by the pipeline resource
      trigger: true

pool:
  name: Azure Pipelines
  vmImage: windows-2019


stages:
  - stage: Production
    displayName: "Production"
    jobs:
      - deployment: "DeploymentProduction"
        displayName: "Deployment Production"
        environment: "AiNewsFetcher-Production"
        variables:
          - group: AiNewsFetcher-Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Release_Steps.yaml
